/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TvSeason } from '../../models/tv-season';

export interface GetTvSeasonById$Params {
  id: (number | string);
  seasonNumber: (number | string);
}

export function getTvSeasonById(http: HttpClient, rootUrl: string, params: GetTvSeasonById$Params, context?: HttpContext): Observable<StrictHttpResponse<TvSeason>> {
  const rb = new RequestBuilder(rootUrl, getTvSeasonById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
    rb.path('seasonNumber', params.seasonNumber, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TvSeason>;
    })
  );
}

getTvSeasonById.PATH = '/media/tv/{id}/season/{seasonNumber}';
