/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TvEpisode } from '../../models/tv-episode';

export interface GetTvEpisodeById$Params {
  id: (number | string);
  seasonNumber: (number | string);
  episodeNumber: (number | string);
}

export function getTvEpisodeById(http: HttpClient, rootUrl: string, params: GetTvEpisodeById$Params, context?: HttpContext): Observable<StrictHttpResponse<TvEpisode>> {
  const rb = new RequestBuilder(rootUrl, getTvEpisodeById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
    rb.path('seasonNumber', params.seasonNumber, {});
    rb.path('episodeNumber', params.episodeNumber, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TvEpisode>;
    })
  );
}

getTvEpisodeById.PATH = '/media/tv/{id}/season/{seasonNumber}/episode/{episodeNumber}';
