/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Movie } from '../../models/movie';

export interface GetMovieById$Params {
  id: number;
}

export function getMovieById(http: HttpClient, rootUrl: string, params: GetMovieById$Params, context?: HttpContext): Observable<StrictHttpResponse<Movie>> {
  const rb = new RequestBuilder(rootUrl, getMovieById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Movie>;
    })
  );
}

getMovieById.PATH = '/media/movie/{id}/id';
