/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SearchContainerOfSearchTv } from '../../models/search-container-of-search-tv';

export interface GetTvShowByTitle$Params {
  term: string;
}

export function getTvShowByTitle(http: HttpClient, rootUrl: string, params: GetTvShowByTitle$Params, context?: HttpContext): Observable<StrictHttpResponse<SearchContainerOfSearchTv>> {
  const rb = new RequestBuilder(rootUrl, getTvShowByTitle.PATH, 'get');
  if (params) {
    rb.path('term', params.term, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SearchContainerOfSearchTv>;
    })
  );
}

getTvShowByTitle.PATH = '/media/tv/{term}/search';
