/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SearchContainerWithDatesOfSearchMovie } from '../../models/search-container-with-dates-of-search-movie';

export interface GetNowPlayingMovies$Params {
}

export function getNowPlayingMovies(http: HttpClient, rootUrl: string, params?: GetNowPlayingMovies$Params, context?: HttpContext): Observable<StrictHttpResponse<SearchContainerWithDatesOfSearchMovie>> {
  const rb = new RequestBuilder(rootUrl, getNowPlayingMovies.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SearchContainerWithDatesOfSearchMovie>;
    })
  );
}

getNowPlayingMovies.PATH = '/media/now/playing';
