/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SearchContainerOfSearchMovie } from '../../models/search-container-of-search-movie';

export interface GetMovieByTitle$Params {
  term: string;
}

export function getMovieByTitle(http: HttpClient, rootUrl: string, params: GetMovieByTitle$Params, context?: HttpContext): Observable<StrictHttpResponse<SearchContainerOfSearchMovie>> {
  const rb = new RequestBuilder(rootUrl, getMovieByTitle.PATH, 'get');
  if (params) {
    rb.path('term', params.term, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SearchContainerOfSearchMovie>;
    })
  );
}

getMovieByTitle.PATH = '/media/movie/{term}/search';
