/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SearchContainerOfTvShow } from '../../models/search-container-of-tv-show';

export interface GetPersonByName$Params {
  term: string;
}

export function getPersonByName(http: HttpClient, rootUrl: string, params: GetPersonByName$Params, context?: HttpContext): Observable<StrictHttpResponse<SearchContainerOfTvShow>> {
  const rb = new RequestBuilder(rootUrl, getPersonByName.PATH, 'get');
  if (params) {
    rb.path('term', params.term, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SearchContainerOfTvShow>;
    })
  );
}

getPersonByName.PATH = '/media/person/{term}/search';
