/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AccountState {
  favorite?: boolean;
  id?: (number | string);
  rating?: (number | string | null);
  watchlist?: boolean;
}
