/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AlternativeTitle } from '../models/alternative-title';
export interface AlternativeTitles {
  id?: (number | string);
  titles?: (Array<AlternativeTitle> | null);
}
