/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AuthorDetails {
  avatarPath?: (string | null);
  name?: (string | null);
  rating?: (number | string | null);
  username?: (string | null);
}
