/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CastRole {
  character?: (string | null);
  creditId?: (string | null);
  episodeCount?: (number | string);
}
