/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CastRole } from '../models/cast-role';
import { PersonGender } from '../models/person-gender';
export interface CastAggregate {
  adult?: boolean;
  gender?: PersonGender;
  id?: (number | string);
  knownForDepartment?: (string | null);
  name?: (string | null);
  order?: (number | string);
  originalName?: (string | null);
  popularity?: (number | string);
  profilePath?: (string | null);
  roles?: (Array<CastRole> | null);
  totalEpisodeCount?: (number | string);
}
