/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PersonGender } from '../models/person-gender';
export interface Cast {
  adult?: boolean;
  castId?: (number | string);
  character?: (string | null);
  creditId?: (string | null);
  gender?: PersonGender;
  id?: (number | string);
  knownForDepartment?: (string | null);
  name?: (string | null);
  order?: (number | string);
  originalName?: (string | null);
  popularity?: (number | string);
  profilePath?: (string | null);
}
