/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ChangeItemBase } from '../models/change-item-base';
export interface Change {
  items?: (Array<ChangeItemBase> | null);
  key?: (string | null);
}
