/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ChangeAction } from '../models/change-action';
export interface ChangeItemBase {
  action?: ChangeAction;
  id?: (string | null);
  iso_639_1?: (string | null);
  time?: string;
}
