/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MediaType } from '../models/media-type';
export interface CombinedCreditsCrewBase {
  backdropPath?: (string | null);
  creditId?: (string | null);
  department?: (string | null);
  genreIds?: (Array<(number | string)> | null);
  id?: (number | string);
  job?: (string | null);
  mediaType?: MediaType;
  originalLanguage?: (string | null);
  overview?: (string | null);
  popularity?: (number | string);
  posterPath?: (string | null);
  voteAverage?: (number | string);
  voteCount?: (number | string);
}
