/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CombinedCreditsCastBase } from '../models/combined-credits-cast-base';
import { CombinedCreditsCrewBase } from '../models/combined-credits-crew-base';
export interface CombinedCredits {
  cast?: (Array<CombinedCreditsCastBase> | null);
  crew?: (Array<CombinedCreditsCrewBase> | null);
  id?: (number | string);
}
