/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Country {
  certification?: (string | null);
  iso_3166_1?: (string | null);
  primary?: boolean;
  releaseDate?: (string | null);
}
