/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateAccountCommand {
  bio: (string | null);
  birthDate: string;
  displayName: string;
  email: string;
  name: string;
  password: string;
  surname: (string | null);
  username: string;
}
