/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PersonGender } from '../models/person-gender';
export interface CreatedBy {
  creditId?: (string | null);
  gender?: PersonGender;
  id?: (number | string);
  name?: (string | null);
  profilePath?: (string | null);
}
