/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CastAggregate } from '../models/cast-aggregate';
import { CrewAggregate } from '../models/crew-aggregate';
export interface CreditsAggregate {
  cast?: (Array<CastAggregate> | null);
  crew?: (Array<CrewAggregate> | null);
  id?: (number | string);
}
