/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Cast } from '../models/cast';
import { Crew } from '../models/crew';
export interface Credits {
  cast?: (Array<Cast> | null);
  crew?: (Array<Crew> | null);
  id?: (number | string);
}
