/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CrewJob } from '../models/crew-job';
import { PersonGender } from '../models/person-gender';
export interface CrewAggregate {
  adult?: boolean;
  department?: (string | null);
  gender?: PersonGender;
  id?: (number | string);
  jobs?: (Array<CrewJob> | null);
  knownForDepartment?: (string | null);
  name?: (string | null);
  originalName?: (string | null);
  popularity?: (number | string);
  profilePath?: (string | null);
  totalEpisodeCount?: (number | string);
}
