/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PersonGender } from '../models/person-gender';
export interface Crew {
  adult?: boolean;
  creditId?: (string | null);
  department?: (string | null);
  gender?: PersonGender;
  id?: (number | string);
  job?: (string | null);
  knownForDepartment?: (string | null);
  name?: (string | null);
  originalName?: (string | null);
  popularity?: (number | string);
  profilePath?: (string | null);
}
