/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ErrorType } from '../models/error-type';
export interface Error {
  code?: (string | null);
  description?: (string | null);
  metadata?: ({
} | null);
  numericType?: (number | string);
  type?: ErrorType;
}
