/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ExternalIdsTvSeason {
  freebaseId?: (string | null);
  freebaseMid?: (string | null);
  id?: (number | string);
  tvdbId?: (string | null);
  tvrageId?: (string | null);
  wikidataId?: (string | null);
}
