/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ExternalIdsPerson {
  facebookId?: (string | null);
  freebaseId?: (string | null);
  freebaseMid?: (string | null);
  id?: (number | string);
  imdbId?: (string | null);
  instagramId?: (string | null);
  tvrageId?: (string | null);
  twitterId?: (string | null);
  wikidataId?: (string | null);
}
