/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ExternalIdsTvEpisode {
  freebaseId?: (string | null);
  freebaseMid?: (string | null);
  id?: (number | string);
  imdbId?: (string | null);
  tvdbId?: (string | null);
  tvrageId?: (string | null);
  wikidataId?: (string | null);
}
