/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ImageData {
  aspectRatio?: (number | string);
  filePath?: (string | null);
  height?: (number | string);
  iso_3166_1?: (string | null);
  iso_639_1?: (string | null);
  voteAverage?: (number | string);
  voteCount?: (number | string);
  width?: (number | string);
}
