/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ImageData } from '../models/image-data';
export interface Images {
  backdrops?: (Array<ImageData> | null);
  logos?: (Array<ImageData> | null);
  posters?: (Array<ImageData> | null);
}
