/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Keyword } from '../models/keyword';
export interface KeywordsContainer {
  id?: (number | string);
  keywords?: (Array<Keyword> | null);
}
