/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MovieRole {
  adult?: boolean;
  backdropPath?: (string | null);
  character?: (string | null);
  creditId?: (string | null);
  genreIds?: (Array<(number | string)> | null);
  id?: (number | string);
  order?: (number | string);
  originalLanguage?: (string | null);
  originalTitle?: (string | null);
  overview?: (string | null);
  popularity?: (number | string);
  posterPath?: (string | null);
  releaseDate?: (string | null);
  title?: (string | null);
  video?: boolean;
  voteAverage?: (number | string);
  voteCount?: (number | string);
}
