/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MovieJob {
  adult?: boolean;
  creditId?: (string | null);
  department?: (string | null);
  id?: (number | string);
  job?: (string | null);
  originalTitle?: (string | null);
  posterPath?: (string | null);
  releaseDate?: (string | null);
  title?: (string | null);
}
