/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MovieJob } from '../models/movie-job';
import { MovieRole } from '../models/movie-role';
export interface MovieCredits {
  cast?: (Array<MovieRole> | null);
  crew?: (Array<MovieJob> | null);
  id?: (number | string);
}
