/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NetworkWithLogo {
  id?: (number | string);
  logoPath?: (string | null);
  name?: (string | null);
  originCountry?: (string | null);
}
