/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ChangesContainer } from '../models/changes-container';
import { CombinedCredits } from '../models/combined-credits';
import { ExternalIdsPerson } from '../models/external-ids-person';
import { MovieCredits } from '../models/movie-credits';
import { PersonGender } from '../models/person-gender';
import { ProfileImages } from '../models/profile-images';
import { SearchContainerOfTaggedImage } from '../models/search-container-of-tagged-image';
import { TranslationsContainer } from '../models/translations-container';
import { TvCredits } from '../models/tv-credits';
export interface Person {
  adult?: boolean;
  alsoKnownAs?: (Array<string> | null);
  biography?: (string | null);
  birthday?: (string | null);
  changes?: (null | ChangesContainer);
  combinedCredits?: (null | CombinedCredits);
  deathday?: (string | null);
  externalIds?: (null | ExternalIdsPerson);
  gender?: PersonGender;
  homepage?: (string | null);
  id?: (number | string);
  images?: (null | ProfileImages);
  imdbId?: (string | null);
  knownForDepartment?: (string | null);
  movieCredits?: (null | MovieCredits);
  name?: (string | null);
  placeOfBirth?: (string | null);
  popularity?: (number | string);
  profilePath?: (string | null);
  taggedImages?: (null | SearchContainerOfTaggedImage);
  translations?: (null | TranslationsContainer);
  tvCredits?: (null | TvCredits);
}
