/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ImageData } from '../models/image-data';
export interface ProfileImages {
  id?: (number | string);
  profiles?: (Array<ImageData> | null);
}
