/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ReleaseDateItem } from '../models/release-date-item';
export interface ReleaseDatesContainer {
  iso_3166_1?: (string | null);
  releaseDates?: (Array<ReleaseDateItem> | null);
}
