/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ReleaseDateType } from '../models/release-date-type';
export interface ReleaseDateItem {
  certification?: (string | null);
  iso_639_1?: (string | null);
  note?: (string | null);
  releaseDate?: string;
  type?: ReleaseDateType;
}
