/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Country } from '../models/country';
export interface Releases {
  countries?: (Array<Country> | null);
  id?: (number | string);
}
