/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AuthorDetails } from '../models/author-details';
export interface ReviewBase {
  author?: (string | null);
  authorDetails?: (null | AuthorDetails);
  content?: (string | null);
  createdAt?: string;
  id?: (string | null);
  updatedAt?: string;
  url?: (string | null);
}
