/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SearchTv } from '../models/search-tv';
export interface SearchContainerOfSearchTv {
  page?: (number | string);
  results?: (Array<SearchTv> | null);
  totalPages?: (number | string);
  totalResults?: (number | string);
}
