/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MediaType } from '../models/media-type';
export interface SearchTvSeason {
  airDate?: (string | null);
  episodeCount?: (number | string);
  id?: (number | string);
  mediaType?: MediaType;
  name?: (string | null);
  overview?: (string | null);
  popularity?: (number | string);
  posterPath?: (string | null);
  seasonNumber?: (number | string);
}
