/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MediaType } from '../models/media-type';
export interface SearchMovie {
  adult?: boolean;
  backdropPath?: (string | null);
  genreIds?: (Array<(number | string)> | null);
  id?: (number | string);
  mediaType?: MediaType;
  originalLanguage?: (string | null);
  originalTitle?: (string | null);
  overview?: (string | null);
  popularity?: (number | string);
  posterPath?: (string | null);
  releaseDate?: (string | null);
  title?: (string | null);
  video?: boolean;
  voteAverage?: (number | string);
  voteCount?: (number | string);
}
