/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MediaType } from '../models/media-type';
export interface SearchCollection {
  adult?: boolean;
  backdropPath?: (string | null);
  id?: (number | string);
  mediaType?: MediaType;
  name?: (string | null);
  originalLanguage?: (string | null);
  originalName?: (string | null);
  overview?: (string | null);
  popularity?: (number | string);
  posterPath?: (string | null);
}
