/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TaggedImage } from '../models/tagged-image';
export interface SearchContainerOfTaggedImage {
  page?: (number | string);
  results?: (Array<TaggedImage> | null);
  totalPages?: (number | string);
  totalResults?: (number | string);
}
