/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ReviewBase } from '../models/review-base';
export interface SearchContainerOfReviewBase {
  page?: (number | string);
  results?: (Array<ReviewBase> | null);
  totalPages?: (number | string);
  totalResults?: (number | string);
}
