/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MediaType } from '../models/media-type';
export interface SearchTv {
  backdropPath?: (string | null);
  firstAirDate?: (string | null);
  genreIds?: (Array<(number | string)> | null);
  id?: (number | string);
  mediaType?: MediaType;
  name?: (string | null);
  originCountry?: (Array<string> | null);
  originalLanguage?: (string | null);
  originalName?: (string | null);
  overview?: (string | null);
  popularity?: (number | string);
  posterPath?: (string | null);
  voteAverage?: (number | string);
  voteCount?: (number | string);
}
