/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MediaType } from '../models/media-type';
export interface SearchBase {
  id?: (number | string);
  mediaType?: MediaType;
  popularity?: (number | string);
}
