/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SearchMovie } from '../models/search-movie';
export interface SearchContainerOfSearchMovie {
  page?: (number | string);
  results?: (Array<SearchMovie> | null);
  totalPages?: (number | string);
  totalResults?: (number | string);
}
