/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DateRange } from '../models/date-range';
import { SearchMovie } from '../models/search-movie';
export interface SearchContainerWithDatesOfSearchMovie {
  dates?: (null | DateRange);
  page?: (number | string);
  results?: (Array<SearchMovie> | null);
  totalPages?: (number | string);
  totalResults?: (number | string);
}
