/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TvShow } from '../models/tv-show';
export interface SearchContainerOfTvShow {
  page?: (number | string);
  results?: (Array<TvShow> | null);
  totalPages?: (number | string);
  totalResults?: (number | string);
}
