/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ImageData } from '../models/image-data';
export interface StillImages {
  id?: (number | string);
  stills?: (Array<ImageData> | null);
}
