/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MediaType } from '../models/media-type';
import { SearchBase } from '../models/search-base';
export interface TaggedImage {
  aspectRatio?: (number | string);
  filePath?: (string | null);
  height?: (number | string);
  id?: (string | null);
  imageType?: (string | null);
  iso_639_1?: (string | null);
  media?: (null | SearchBase);
  mediaType?: MediaType;
  voteAverage?: (number | string);
  voteCount?: (number | string);
  width?: (number | string);
}
