/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TranslationData {
  homePage?: (string | null);
  name?: (string | null);
  overview?: (string | null);
  runtime?: (number | string);
  tagline?: (string | null);
}
