/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TranslationData } from '../models/translation-data';
export interface Translation {
  data?: (null | TranslationData);
  englishName?: (string | null);
  iso_3166_1?: (string | null);
  iso_639_1?: (string | null);
  name?: (string | null);
}
