/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Translation } from '../models/translation';
export interface TranslationsContainer {
  id?: (number | string);
  translations?: (Array<Translation> | null);
}
