/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TvJob } from '../models/tv-job';
import { TvRole } from '../models/tv-role';
export interface TvCredits {
  cast?: (Array<TvRole> | null);
  crew?: (Array<TvJob> | null);
  id?: (number | string);
}
