/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TvEpisodeBase {
  airDate?: (string | null);
  episodeNumber?: (number | string);
  episodeType?: (string | null);
  id?: (number | string | null);
  name?: (string | null);
  overview?: (string | null);
  productionCode?: (string | null);
  runtime?: (number | string | null);
  seasonNumber?: (number | string);
  showId?: (number | string);
  stillPath?: (string | null);
  voteAverage?: (number | string);
  voteCount?: (number | string);
}
