/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TvEpisodeAccountStateWithNumber {
  episodeNumber?: (number | string);
  id?: (number | string);
  rating?: (number | string | null);
}
