/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Cast } from '../models/cast';
import { CreditsWithGuestStars } from '../models/credits-with-guest-stars';
import { Crew } from '../models/crew';
import { ExternalIdsTvEpisode } from '../models/external-ids-tv-episode';
import { ResultContainerOfVideo } from '../models/result-container-of-video';
import { StillImages } from '../models/still-images';
import { TranslationsContainer } from '../models/translations-container';
import { TvAccountState } from '../models/tv-account-state';
export interface TvEpisode {
  accountStates?: (null | TvAccountState);
  airDate?: (string | null);
  credits?: (null | CreditsWithGuestStars);
  crew?: (Array<Crew> | null);
  episodeNumber?: (number | string);
  episodeType?: (string | null);
  externalIds?: (null | ExternalIdsTvEpisode);
  guestStars?: (Array<Cast> | null);
  id?: (number | string | null);
  images?: (null | StillImages);
  name?: (string | null);
  overview?: (string | null);
  productionCode?: (string | null);
  runtime?: (number | string | null);
  seasonNumber?: (number | string);
  showId?: (number | string);
  stillPath?: (string | null);
  translations?: (null | TranslationsContainer);
  videos?: (null | ResultContainerOfVideo);
  voteAverage?: (number | string);
  voteCount?: (number | string);
}
