/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NetworkWithLogo } from '../models/network-with-logo';
import { TvGroup } from '../models/tv-group';
import { TvGroupType } from '../models/tv-group-type';
export interface TvGroupCollection {
  description?: (string | null);
  episodeCount?: (number | string);
  groupCount?: (number | string);
  groups?: (Array<TvGroup> | null);
  id?: (string | null);
  name?: (string | null);
  network?: (null | NetworkWithLogo);
  type?: TvGroupType;
}
