/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TvGroupEpisode } from '../models/tv-group-episode';
export interface TvGroup {
  episodes?: (Array<TvGroupEpisode> | null);
  id?: (string | null);
  locked?: boolean;
  name?: (string | null);
  order?: (number | string);
}
