/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TvJob {
  creditId?: (string | null);
  department?: (string | null);
  episodeCount?: (number | string);
  firstAirDate?: (string | null);
  id?: (number | string);
  job?: (string | null);
  name?: (string | null);
  originalName?: (string | null);
  posterPath?: (string | null);
}
