/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TvRole {
  character?: (string | null);
  creditId?: (string | null);
  episodeCount?: (number | string);
  firstAirDate?: (string | null);
  id?: (number | string);
  name?: (string | null);
  originalName?: (string | null);
  posterPath?: (string | null);
}
