/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Credits } from '../models/credits';
import { ExternalIdsTvSeason } from '../models/external-ids-tv-season';
import { PosterImages } from '../models/poster-images';
import { ResultContainerOfTvEpisodeAccountStateWithNumber } from '../models/result-container-of-tv-episode-account-state-with-number';
import { ResultContainerOfVideo } from '../models/result-container-of-video';
import { TranslationsContainer } from '../models/translations-container';
import { TvSeasonEpisode } from '../models/tv-season-episode';
export interface TvSeason {
  accountStates?: (null | ResultContainerOfTvEpisodeAccountStateWithNumber);
  airDate?: (string | null);
  credits?: (null | Credits);
  episodes?: (Array<TvSeasonEpisode> | null);
  externalIds?: (null | ExternalIdsTvSeason);
  id?: (number | string | null);
  images?: (null | PosterImages);
  name?: (string | null);
  overview?: (string | null);
  posterPath?: (string | null);
  seasonNumber?: (number | string);
  translations?: (null | TranslationsContainer);
  videos?: (null | ResultContainerOfVideo);
  voteAverage?: (number | string);
}
