/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Cast } from '../models/cast';
import { Crew } from '../models/crew';
export interface TvSeasonEpisode {
  airDate?: (string | null);
  crew?: (Array<Crew> | null);
  episodeNumber?: (number | string);
  episodeType?: (string | null);
  guestStars?: (Array<Cast> | null);
  id?: (number | string);
  name?: (string | null);
  overview?: (string | null);
  productionCode?: (string | null);
  runtime?: (number | string | null);
  seasonNumber?: (number | string);
  stillPath?: (string | null);
  voteAverage?: (number | string);
  voteCount?: (number | string);
}
