/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Video {
  id?: (string | null);
  iso_3166_1?: (string | null);
  iso_639_1?: (string | null);
  key?: (string | null);
  name?: (string | null);
  official?: boolean;
  publishedAt?: string;
  site?: (string | null);
  size?: (number | string);
  type?: (string | null);
}
