/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { WatchProviderItem } from '../models/watch-provider-item';
export interface WatchProviders {
  ads?: (Array<WatchProviderItem> | null);
  buy?: (Array<WatchProviderItem> | null);
  flatRate?: (Array<WatchProviderItem> | null);
  free?: (Array<WatchProviderItem> | null);
  link?: (string | null);
  rent?: (Array<WatchProviderItem> | null);
}
