/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface WatchProviderItem {
  displayPriority?: (number | string | null);
  logoPath?: (string | null);
  providerId?: (number | string | null);
  providerName?: (string | null);
}
